### ISSUE TITLE
[Visual Improvement] Add a dark scrollbar for chrome & safari

### ISSUE THREAD

**Issue by LilyKensa** [misenhower/splatoon3.ink#77]
As the title says, when using chrome, we got a very white scrollbar that conflicts a lot with the website's style.

<img width="1280" alt="image" src="https://github.com/misenhower/splatoon3.ink/assets/89726427/234debcb-f894-4878-8ec5-62be678082b6">

I hope we got something like this instead:

<img width="1280" alt="image" src="https://github.com/misenhower/splatoon3.ink/assets/89726427/cd7d3f1f-d8ce-4f2d-bb7c-1ca0de5c69dd">

My CSS code:

```css
body::-webkit-scrollbar {
    width: 12px;
    height: 12px;
}

body::-webkit-scrollbar-thumb {
    background-color: #515151;
    border-radius: 10px;
    border: 2px solid transparent;
    background-clip: content-box;
}
body::-webkit-scrollbar-thumb:hover {
    background-color: #5b5b5b;
}
body::-webkit-scrollbar-thumb:active {
    background-color: #6d6d6d;
}

body::-webkit-scrollbar-track {
    background-color: #161616;
}
```
